# Generated by Django 3.0.3 on 2020-02-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0002_auto_20200219_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='City name', max_length=50)),
                ('population', models.IntegerField()),
                ('climate', models.CharField(choices=[('D', 'Discomfort'), ('C', 'Comfort')], default='C', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.City')),
            ],
        ),
        migrations.CreateModel(
            name='ListIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.City')),
                ('indicator', models.ManyToManyField(to='city.Indicator')),
            ],
        ),
    ]
