# Generated by Django 3.0.3 on 2020-02-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_city_indicator_listindicators_region'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='Cities',
        ),
    ]
