# Generated by Django 3.0.3 on 2020-02-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_auto_20200219_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listindicators',
            name='indicator',
        ),
        migrations.AddField(
            model_name='listindicators',
            name='indicator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city.Indicator'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
    ]
