# Generated by Django 3.0.3 on 2020-02-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_auto_20200219_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='cities',
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.Region'),
        ),
    ]
