# Generated by Django 3.0.3 on 2020-02-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0006_auto_20200219_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
